'use strict';
/**
 * Shared PDF report layout for DocAudit AI reports.
 *
 * Reproduces a consistent, professional structure across every exported report:
 *   1. Branded header  — logo + company on the left, contact details on the right,
 *                        followed by a thick brand divider.
 *   2. Report details  — "REPORT DETAILS" heading with an orange rule and the
 *                        key facts (report name, period, prepared by, date), closed
 *                        off with a green rule.
 *   3. Centered title  — the report name with its month/year.
 *   4. Body            — (caller renders tables / sections / score visuals).
 *   5. Signature block — Prepared By, Signature line, Date.
 *   6. Footer          — "Generated By DocAudit AI" + page numbers on every page.
 *
 * Contact email / website can be overridden with env vars so the branding stays flexible.
 */
const fs = require('fs');
const path = require('path');

const LOGO_PATH = path.join(__dirname, '..', 'assets', 'sifco-logo.png');
const LOGO_EXISTS = fs.existsSync(LOGO_PATH);

const BRAND = {
  company: 'Super International Freight / SIFCO',
  name: 'DOCAUDIT AI',
  taglines: ['COMPLIANCE & AUDIT PLATFORM', 'DOCUMENT REVIEW SYSTEM'],
  email: process.env.REPORT_CONTACT_EMAIL || 'compliance@sifco.com',
  website: process.env.REPORT_CONTACT_WEBSITE || 'www.sifco.com',
  footer: 'Generated By DocAudit AI',
};

const COLORS = {
  navy: '#1f3a5f',
  navyText: '#1a2b48',
  orange: '#e8702a',
  green: '#2e8b57',
  text: '#1a1d24',
  body: '#374151',
  muted: '#6b7280',
  faint: '#9ca3af',
  line: '#e5e7eb',
  zebra: '#f9fafb',
  danger: '#dc2626',
  warn: '#e8702a',
  good: '#16a34a',
};

function fmtDate(d) {
  if (!d) return '—';
  const dt = new Date(d);
  if (isNaN(dt.getTime())) return '—';
  return dt.toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' });
}

function monthYear(d) {
  const dt = d ? new Date(d) : new Date();
  return dt.toLocaleDateString('en-US', { month: 'short', year: 'numeric' });
}

/** Branded header. Returns the y position to continue rendering below it. */
function drawHeader(doc) {
  const pageW = doc.page.width;
  const left = doc.page.margins.left;
  const right = pageW - doc.page.margins.right;
  const top = 28;

  // Logo sits top-left; the company/brand text is stacked beneath it so a wide
  // logo never overlaps the wordmark.
  let textTop = top;
  if (LOGO_EXISTS) {
    const logoH = 32;
    try {
      doc.image(LOGO_PATH, left, top, { height: logoH });
      textTop = top + logoH + 8;
    } catch (e) { textTop = top; }
  }

  const leftW = Math.max(220, (right - 230) - left);

  doc.fillColor(COLORS.text).font('Helvetica-Bold').fontSize(12)
    .text(BRAND.company, left, textTop, { width: leftW, lineBreak: false, ellipsis: true });
  doc.fillColor(COLORS.navyText).font('Helvetica-Bold').fontSize(9)
    .text(BRAND.name, left, textTop + 16, { width: leftW, lineBreak: false });
  doc.fillColor(COLORS.navyText).font('Helvetica-Bold').fontSize(7.5)
    .text(BRAND.taglines[0], left, textTop + 28, { width: leftW, lineBreak: false })
    .text(BRAND.taglines[1], left, textTop + 37, { width: leftW, lineBreak: false });

  // Contact details, right-aligned at the top.
  const contactW = 220;
  const contactX = right - contactW;
  doc.fillColor(COLORS.navyText).font('Helvetica-Bold').fontSize(9)
    .text(BRAND.email, contactX, top + 2, { width: contactW, align: 'right', lineBreak: false })
    .text(BRAND.website, contactX, top + 16, { width: contactW, align: 'right', lineBreak: false });

  const lineY = textTop + 50;
  doc.moveTo(left, lineY).lineTo(right, lineY).lineWidth(2.5).strokeColor(COLORS.navy).stroke();
  return lineY + 16;
}

/**
 * "REPORT DETAILS" block.
 * @param {Array<[string, any]>} pairs - key/value lines.
 * @param {string} reportName - bold report name shown first.
 */
function drawReportDetails(doc, y, pairs, reportName) {
  const left = doc.page.margins.left;
  const right = doc.page.width - doc.page.margins.right;

  doc.fillColor(COLORS.navyText).font('Helvetica-Bold').fontSize(12).text('REPORT DETAILS', left, y);
  y += 18;
  doc.moveTo(left, y).lineTo(right, y).lineWidth(2).strokeColor(COLORS.orange).stroke();
  y += 10;

  if (reportName) {
    doc.fillColor(COLORS.text).font('Helvetica-Bold').fontSize(11).text(String(reportName), left, y, { width: right - left });
    y += 18;
  }

  (pairs || []).forEach(function (pair) {
    const key = pair[0];
    const val = pair[1];
    doc.font('Helvetica-Bold').fontSize(10).fillColor(COLORS.text)
      .text(key + ': ', left, y, { continued: true });
    doc.font('Helvetica').fillColor(COLORS.body).text(String(val == null || val === '' ? '—' : val));
    y += 16;
  });

  y += 6;
  doc.moveTo(left, y).lineTo(right, y).lineWidth(2).strokeColor(COLORS.green).stroke();
  return y + 18;
}

/** Centered report title (e.g. "My Report – Jun 2026"). */
function drawCenteredTitle(doc, y, title) {
  const left = doc.page.margins.left;
  const width = doc.page.width - doc.page.margins.left - doc.page.margins.right;
  doc.fillColor(COLORS.text).font('Helvetica-Bold').fontSize(17)
    .text(String(title || 'Report'), left, y, { width: width, align: 'center' });
  return y + 32;
}

/** Prepared By / Signature / Date block. */
function drawSignatureBlock(doc, y, preparedBy) {
  const left = doc.page.margins.left;
  if (y > doc.page.height - 140) { doc.addPage(); y = 60; }
  y += 14;

  doc.fillColor(COLORS.text).font('Helvetica-Bold').fontSize(10)
    .text('Prepared By: ', left, y, { continued: true })
    .font('Helvetica').text(preparedBy || '—');
  y += 24;

  doc.font('Helvetica-Bold').fillColor(COLORS.text)
    .text('Signature: ', left, y, { continued: true })
    .font('Helvetica').text('_______________________________________');
  y += 24;

  doc.font('Helvetica-Bold').fillColor(COLORS.text)
    .text('Date: ', left, y, { continued: true })
    .font('Helvetica').text(fmtDate(new Date()));
  return y + 22;
}

/** "Generated By DocAudit AI" footer + page numbers on every buffered page. */
function drawFooter(doc) {
  const range = doc.bufferedPageRange();
  for (let i = range.start; i < range.start + range.count; i++) {
    doc.switchToPage(i);
    doc.page.margins.bottom = 0; // keep the footer from spawning blank pages
    const footerY = doc.page.height - 30;
    doc.fontSize(9).font('Helvetica-Oblique').fillColor(COLORS.faint)
      .text(BRAND.footer, 50, footerY, { align: 'center', width: doc.page.width - 100, lineBreak: false });
    doc.fontSize(7.5).font('Helvetica').fillColor(COLORS.faint)
      .text('Page ' + (i - range.start + 1) + ' of ' + range.count,
        doc.page.width - 120, footerY, { width: 70, align: 'right', lineBreak: false });
  }
}

/**
 * Colour for a table cell based on its column label + value
 * (Severity: critical/major/minor, Status: pass/fail, etc.). Returns null when neutral.
 */
function cellColor(label, value) {
  const key = String(label || '').toLowerCase();
  const v = String(value == null ? '' : value).toLowerCase();
  if (!v) return null;

  if (/sever|risk|priority/.test(key)) {
    if (/critical|high|urgent/.test(v)) return COLORS.danger;
    if (/major|medium|warn/.test(v)) return COLORS.warn;
    if (/minor|low|info/.test(v)) return COLORS.good;
  }
  if (/status|outcome|result|stage|decision/.test(key)) {
    if (/fail|reject|overdue|error|breach/.test(v)) return COLORS.danger;
    if (/pass|approv|complete|success|resolved/.test(v)) return COLORS.good;
    if (/pending|review|flag|warn|in.?progress|revision/.test(v)) return COLORS.warn;
  }
  return null;
}

/**
 * Detect whether the supplied document text is a report produced by this system
 * (a DocAudit AI / SIFCO audit or role report). Used by the audit engine to treat
 * its own output as inherently valid instead of flagging it as a forgery or an
 * untrained document.
 */
function isSystemGeneratedReport(text) {
  if (!text) return false;
  const t = String(text).toLowerCase();

  // Strongest marker: the exact footer stamped on every generated report.
  if (t.indexOf('generated by docaudit ai') >= 0) return true;

  // Otherwise require the brand AND the report structure together, so that an
  // ordinary shipping document that merely mentions SIFCO is not misclassified.
  const hasBrand = t.indexOf('docaudit ai') >= 0
    || (t.indexOf('super international freight') >= 0 && t.indexOf('sifco') >= 0);
  const hasStructure = t.indexOf('report details') >= 0
    || (t.indexOf('prepared by') >= 0 && t.indexOf('date generated') >= 0)
    || (t.indexOf('compliance & audit platform') >= 0 && t.indexOf('document review system') >= 0);

  return hasBrand && hasStructure;
}

module.exports = {
  BRAND: BRAND,
  COLORS: COLORS,
  isSystemGeneratedReport: isSystemGeneratedReport,
  LOGO_PATH: LOGO_PATH,
  LOGO_EXISTS: LOGO_EXISTS,
  fmtDate: fmtDate,
  monthYear: monthYear,
  drawHeader: drawHeader,
  drawReportDetails: drawReportDetails,
  drawCenteredTitle: drawCenteredTitle,
  drawSignatureBlock: drawSignatureBlock,
  drawFooter: drawFooter,
  cellColor: cellColor,
};
