/**
 * Analysis Controller
 * Real AI audit engine — rule-based + optional OpenAI
 * Extracts text from PDF/DOCX files, runs full compliance audit
 */

const fs   = require('fs');
const path = require('path');
const { Op } = require('sequelize');
const aiService = require('../services/aiService');
const emailService = require('../services/emailService');
const reportLayout = require('../services/reportLayout');
const shipmentConsistency = require('../services/sifcoShipmentConsistencyService');
const notebookAudit = require('../services/sifcoNotebookAuditService');
const { resolveNeedsAuditNotifications } = require('./documentController');
const { userOwnsDocument } = require('../utils/ownerScope');
const { isExportFormatAllowed, allowedExportFormats, normalizeRole } = require('../utils/roles');
const { streamDocumentAnalysisPdf } = require('../services/documentAnalysisReportService');
const { extractTextFromFile, resolveExistingPath, isImageFile } = require('../services/pdfTextService');

/**
 * Exception for the audit engine: reports generated by this system
 * (DocAudit AI / SIFCO audit & role reports) are trusted output and are
 * therefore valid by definition. This mutates the audit `result` so the stored
 * analysis reflects a clean, approved outcome and returns the matching decision.
 */
function systemReportDecision(result) {
  result.organization_match = true;
  result.organization_message = 'Verified DocAudit AI report — trusted system output.';

  var inspection = result.document_inspection;
  if (inspection && inspection.forgery_analysis) {
    var forgery = inspection.forgery_analysis;
    forgery.is_suspicious = false;
    forgery.forgery_score = Math.min(Number(forgery.forgery_score) || 0, 5);
    forgery.risk_level = 'LOW';
    forgery.system_generated = true;
  }

  if (result.compliance_score == null || result.compliance_score < 90) result.compliance_score = 100;
  if (result.overall_audit_score == null || result.overall_audit_score < 90) result.overall_audit_score = 100;
  result.overall_audit_status = 'Excellent';
  result.ai_threshold_exceeded = false;
  result.risk_level = 'low';
  result.system_generated_report = true;

  return {
    status: 'approved',
    title: 'DocAudit AI report validated',
    reason: 'This document is an official report generated by DocAudit AI / SIFCO and is trusted by the system.',
    detail: 'System-generated reports are exempt from forgery and training-match checks.',
    nextSteps: [
      'No action required — this is a verified system report.',
      'Use it directly for compliance evidence or distribution.',
    ],
    code: 'SYSTEM-REPORT-OK',
  };
}

function buildAuditAnalysisSummary(result) {
  var forgery = result.document_inspection && result.document_inspection.forgery_analysis;
  var forgeryScore = Number(forgery && forgery.forgery_score) || 0;
  var forgeryBlocked = !!(forgery && forgery.is_suspicious && forgeryScore >= 45);
  var validated = !!result.trained_reference_match;
  var mlOk = !!result.organization_match;
  var overall = result.overall_audit_score != null ? result.overall_audit_score : result.compliance_score;
  var scoreOk = typeof overall === 'number' ? overall >= 60 : validated || mlOk;
  var aiBlocked = !!result.ai_threshold_exceeded;
  var aiPct = Number(result.ai_generated_percentage) || 0;
  var aiThreshold = (result.ai_detection && result.ai_detection.threshold_percent) || 25;
  var missingFields = result.missing_fields || [];
  var mandatoryMissing = notebookAudit.hasMandatoryMissing(
    missingFields,
    (result.violations || []).map(function (v) {
      return { severity: v.severity, message: v.summary, check: v.title };
    })
  );
  var hasCritical = (result.violations || []).some(function (v) { return v.severity === 'CRITICAL'; });

  var base = {
    status: 'pending_auditor',
    awaitingAuditor: true,
  };

  if ((validated || (mlOk && scoreOk && !mandatoryMissing && !hasCritical)) && !forgeryBlocked && !aiBlocked) {
    var ml = result.organization_training && result.organization_training.ml_training;
    var ref = ml && ml.best_match ? ml.best_match.reference_pdf : '';
    return Object.assign({}, base, {
      title: 'Strong SIFCO document match',
      reason: result.organization_message,
      detail: ref ? 'Matched training reference: ' + ref : result.summary,
      nextSteps: [
        'Review findings and set status to approved, changes requested, or rejected.',
        'Scores at 60% or above are generally acceptable pending your review.',
      ],
      code: 'ML-OK',
      scoreBand: overall >= 60 ? 'good' : 'review',
    });
  }

  if (forgeryBlocked) {
    return Object.assign({}, base, {
      title: 'Document integrity concerns',
      reason: result.organization_message || ('Forgery risk score ' + forgeryScore + '/100 exceeds threshold.'),
      detail: (forgery.flags || []).slice(0, 5).join('; ') || 'Visual or text integrity indicators flagged this document.',
      nextSteps: [
        'Verify stamps, signatures, and letterhead against the original SIFCO reference.',
        'Set status to rejected or changes requested after your review.',
      ],
      code: 'FORGERY-FLAG',
      scoreBand: 'failed',
    });
  }

  var calculationErrors = result.calculation_errors || [];
  var hasCalcErrors = calculationErrors.length > 0 ||
    (result.violations || []).some(function (v) { return v.title === 'Calculation Error'; });

  if (hasCalcErrors && mlOk) {
    return Object.assign({}, base, {
      title: 'Calculation errors detected',
      reason: result.organization_message || 'Document totals or line calculations do not match.',
      detail: (calculationErrors.length
        ? calculationErrors.slice(0, 6).join('; ')
        : (result.violations || []).filter(function (v) { return v.title === 'Calculation Error'; }).map(function (v) { return v.summary; }).join('; ')) +
        (typeof overall === 'number' ? (' Compliance score: ' + overall + '%.') : ''),
      nextSteps: [
        'Verify line items, subtotals, and TOTAL against the original document.',
        'Set status to changes requested or rejected until calculations are corrected.',
      ],
      code: 'CALC-ERROR',
      scoreBand: 'failed',
    });
  }

  if (mandatoryMissing || (hasCritical && mlOk)) {
    var scoreNote = typeof overall === 'number' ? (' Compliance score: ' + overall + '%.') : '';
    var isValidIncomplete = mlOk && !hasCritical;
    return Object.assign({}, base, {
      title: isValidIncomplete ? 'Valid SIFCO type — fields incomplete' : 'Required SIFCO fields missing',
      reason: result.organization_message || 'Document is missing required fields for this paper type.',
      detail: (missingFields.length
        ? 'Missing fields: ' + missingFields.slice(0, 8).join(', ') + '.'
        : ((result.violations || []).filter(function (v) { return v.severity === 'CRITICAL'; })[0] || {}).summary || '') + scoreNote,
      nextSteps: [
        'Consider changes requested if the document is valid but incomplete.',
        'Use rejected only if the document cannot be accepted.',
      ],
      code: 'MISSING-FIELDS',
      scoreBand: overall >= 60 ? 'review' : 'failed',
    });
  }

  if (aiBlocked && mlOk && scoreOk) {
    return Object.assign({}, base, {
      title: 'AI-generated content detected',
      reason: 'Authenticity check failed: ' + aiPct + '% of the content is likely AI-generated (limit ' + aiThreshold + '%).',
      detail: (result.ai_detection && result.ai_detection.detail) ||
        'The document text shows strong signs of being machine-generated rather than an authentic SIFCO record.',
      nextSteps: [
        'Confirm the document was produced by a person, not an AI text generator.',
        'Set the final status after your review.',
      ],
      code: 'AI-CONTENT-FLAG',
      scoreBand: 'failed',
    });
  }

  return Object.assign({}, base, {
    title: 'Document not from our company',
    reason: result.organization_message || 'This document does not match any SIFCO trained reference document.',
    detail: (result.inconsistencies && result.inconsistencies[0] && result.inconsistencies[0].detail) || '',
    nextSteps: [
      'Confirm the document is an official SIFCO operations paper (packing list, HBL, shipping agreement, freight invoice, trucking invoice, or sea freight invoice).',
      'Set status to rejected if the document is from outside the company.',
    ],
    code: 'NOT-COMPANY-DOC',
    scoreBand: 'failed',
  });
}

/** @deprecated alias — analysis summary only; auditor sets workflow status */
function decideDocumentStatus(result) {
  return buildAuditAnalysisSummary(result);
}

async function notifyAuditCompletion(models, document, result, decision, auditor, auditorComment = '') {
  const { Notification, User } = models;
  const [owner, auditorUser] = await Promise.all([
    document.uploadedBy ? User.findByPk(document.uploadedBy, { attributes: ['id', 'email', 'fullName', 'role'] }) : null,
    auditor?.id ? User.findByPk(auditor.id, { attributes: ['id', 'email', 'fullName', 'role'] }) : null,
  ]);

  const shortMessage =
    `The audit for "${document.title}" has been completed. ` +
    'Log in to the portal to view the status and full analysis.';

  const recipients = [owner, auditorUser]
    .filter(Boolean)
    .filter((user, index, all) => all.findIndex(u => u.id === user.id) === index);

  await Promise.all(recipients.map(user => Notification.create({
    recipientId: user.id,
    notificationType: user.id === auditorUser?.id ? 'audit_result_recorded' : 'document_audit_completed',
    channel: 'in_app',
    priority: decision.status === 'approved' ? 'medium' : 'high',
    subject: `Audit complete: ${document.title}`,
    message: shortMessage,
    details: {
      documentId: document.id,
      status: decision.status,
      auditorComment: auditorComment || null,
      complianceScore: result.compliance_score,
      aiGeneratedPercentage: result.ai_generated_percentage,
      riskLevel: result.risk_level,
      recipientRole: user.id === auditorUser?.id ? 'auditor' : 'document_owner',
      decisionTitle: decision.title || null,
      decisionReason: decision.reason || null,
      decisionDetail: decision.detail || null,
    },
    relatedEntityType: 'document',
    relatedEntityId: document.id,
    actionUrl: `/documents?documentId=${document.id}`,
    status: 'unread',
    sentAt: new Date(),
    deliveryStatus: 'sent',
  })));

  const portalUrl = process.env.PORTAL_URL || 'http://localhost:3000/documents';

  if (owner?.email) {
    await emailService.sendAuditComplete(
      owner.email,
      owner.fullName || owner.email,
      document.title,
      auditorUser?.fullName || auditor?.email || 'Auditor',
      decision.status,
      shortMessage,
      portalUrl
    );
  }

  if (auditorUser?.email && auditorUser.id !== owner?.id) {
    await emailService.sendEmail({
      to: auditorUser.email,
      subject: `Audit complete: "${document.title}"`,
      html: `
        <p>Hi <strong>${auditorUser.fullName || auditorUser.email}</strong>,</p>
        <p>Your audit for <strong>"${document.title}"</strong> has been recorded.</p>
        <p>Log in to the portal to view the status and full analysis.</p>
        <p><a href="${portalUrl}">Open portal</a></p>
      `,
      text: `Hi ${auditorUser.fullName || auditorUser.email},\n\nYour audit for "${document.title}" has been recorded.\n\nLog in to the portal to view the status and full analysis:\n${portalUrl}`,
    });
  }
}

// ── POST /api/analysis/:documentId/analyze ────────────────────────────────────

const analyzeDocument = async (req, res) => {
  try {
    if (req.user?.role !== 'auditor') {
      return res.status(403).json({ error: 'Only approved auditors can run document audits.' });
    }

    const { documentId } = req.params;
    const auditorComment = (req.body?.auditorComment || req.body?.comment || '').trim();
    const documentTypeHint = (req.body?.documentTypeHint || req.body?.document_type || '').trim() || null;
    const { Document, DocumentAnalysis } = req.app.locals.models;

    const document = await Document.findByPk(documentId);
    if (!document) return res.status(404).json({ error: 'Document not found' });

    // Always re-extract from file so audit uses full document text (not stale sparse cache)
    let textToAnalyze = null;
    const filePath = resolveExistingPath(document.filePath);
    if (filePath) {
      textToAnalyze = await extractTextFromFile(filePath, document.mimeType);
      if (textToAnalyze) {
        await document.update({ extractedText: textToAnalyze.slice(0, 10000), ocrProcessed: true });
      } else {
        console.warn('[analyze] text extraction returned empty for', document.fileName || document.id);
      }
    } else if (document.filePath) {
      console.warn('[analyze] file not found on disk for', document.fileName || document.id, document.filePath);
    }
    if (!textToAnalyze) {
      textToAnalyze = document.extractedText || null;
    }

    // 2. No metadata fallback for audit — file name/title do not identify SIFCO papers
    if (!textToAnalyze || textToAnalyze.trim().length < 25) {
      const isImage = filePath && isImageFile(filePath, document.mimeType);
      return res.status(422).json({
        error: isImage
          ? 'Could not read enough text from this photo. Use a clear, well-lit image of the document (not a blurry WhatsApp screenshot), or upload a searchable PDF or DOCX instead.'
          : 'Could not read document content. Renaming the file does not change the audit — the system reads text inside the document (letterhead, SIFCO, amounts, B/L). Re-upload a searchable PDF, DOCX, or a clear photo and analyze again.',
        documentId,
        fileName: document.fileName,
        hint: isImage ? 'ocr_failed' : 'filename_ignored',
      });
    }

    // 3. ML audit — content only (filename is NOT passed to the classifier)
    const result = await aiService.auditDocument(textToAnalyze, [], {
      contentOnly: true,
      filePath: filePath || document.filePath,
      documentTypeHint,
    });
    let decision = buildAuditAnalysisSummary(result);
    const isSystemReport = reportLayout.isSystemGeneratedReport(textToAnalyze);
    if (isSystemReport) {
      decision = systemReportDecision(result);
    }

    const analysisPayload = {
      analysisType:    'compliance_audit',
      status:          'completed',
      summary:         result.summary       || '',
      results: {
        compliance_score:    result.compliance_score,
        overall_audit_score: result.overall_audit_score,
        overall_audit_status: result.overall_audit_status,
        overall_audit_breakdown: result.overall_audit_breakdown,
        ai_generated_percentage: result.ai_generated_percentage,
        ai_threshold_exceeded: result.ai_threshold_exceeded,
        ai_validity_percentage: result.ai_validity_percentage,
        ai_detection:        result.ai_detection,
        risk_level:          result.risk_level,
        missing_fields:      result.missing_fields,
        extracted_fields:    result.extracted_fields,
        violations:          result.violations,
        inconsistencies:     result.inconsistencies,
        fraud_flags:         result.fraud_flags,
        dataset_baseline:    result.dataset_baseline,
        document_type:       result.document_type,
        organization_match:  result.organization_match,
        organization_message: result.organization_message,
        organization_training: result.organization_training,
        ml_training: result.organization_training?.ml_training,
        decision,
        engine: result.engine,
        document_inspection: result.document_inspection,
        auditor_comment:     auditorComment || null,
      },
      keywords:        result.missing_fields || [],
      recommendations: result.recommendations || [],
      riskFactors:     { level: result.risk_level, flags: result.fraud_flags || [] },
      confidence:      result.ai_validity_percentage !== undefined ? (result.ai_validity_percentage / 100) : 0.95,
      model:           result.engine || 'rule-based-v4',
      performedBy:     req.user?.id || null,
      completedAt:     new Date(),
    };

    const existingAnalysis = await DocumentAnalysis.findOne({ where: { documentId } });
    if (existingAnalysis) {
      await existingAnalysis.update(analysisPayload);
    } else {
      await DocumentAnalysis.create({ documentId, ...analysisPayload });
    }

    await document.update({
      status: isSystemReport ? 'approved' : 'in_progress',
      ocrProcessed: Boolean(textToAnalyze) || document.ocrProcessed,
      metadata: {
        ...(document.metadata || {}),
        latestAuditDecision: decision,
        latestAuditSummary: result.summary,
        latestAuditorComment: auditorComment || null,
        latestComplianceScore: result.compliance_score,
        latestOverallAuditScore: result.overall_audit_score,
        latestOverallAuditStatus: result.overall_audit_status,
        latestAiGeneratedPercentage: result.ai_generated_percentage,
        statusReason: decision.reason,
        statusTitle: decision.title,
        statusDetail: decision.detail,
        statusNextSteps: decision.nextSteps,
        statusCode: decision.code,
        awaitingAuditorDecision: !isSystemReport,
      },
      lastModifiedBy: req.user?.id || null,
      lastModifiedAt: new Date(),
    });

    if (isSystemReport) {
      await resolveNeedsAuditNotifications(req.app.locals.models, documentId);
      notifyAuditCompletion(req.app.locals.models, document, result, decision, req.user, auditorComment)
        .catch((notifyError) => {
          console.warn('Audit completion notification failed:', notifyError.message);
        });
    }

    res.json({
      message:  'Document analysis complete',
      engine:   result.engine,
      analysis: {
        documentId,
        documentTitle:    document.title,
        documentType:     result.document_type,
        compliance_score: result.compliance_score,
        overall_audit_score: result.overall_audit_score,
        overall_audit_status: result.overall_audit_status,
        overall_audit_breakdown: result.overall_audit_breakdown,
        ai_generated_percentage: result.ai_generated_percentage,
        ai_threshold_exceeded: result.ai_threshold_exceeded,
        ai_validity_percentage: result.ai_validity_percentage,
        ai_detection:     result.ai_detection,
        missing_fields:   result.missing_fields,
        extracted_fields: result.extracted_fields,
        inconsistencies:  result.inconsistencies,
        violations:       result.violations,
        fraud_flags:      result.fraud_flags,
        recommendations:  result.recommendations || [],
        ml_training:      result.organization_training && result.organization_training.ml_training,
        sentiment:        result.sentiment,
        risk_level:       result.risk_level,
        riskLevel:        result.risk_level,
        summary:          result.summary,
        policy_rules_checked: result.policy_rules_checked,
        engine:           result.engine,
        dataset_baseline: result.dataset_baseline,
        decision,
        document_inspection: result.document_inspection,
        auditor_comment: auditorComment || null,
        analyzedAt:       new Date(),
      },
    });
  } catch (error) {
    console.error('Analyze document error:', error);
    res.status(500).json({ error: error.message || 'Analysis failed' });
  }
};

// ── POST /api/analysis/text — analyze raw pasted/uploaded text ────────────────

const analyzeText = async (req, res) => {
  try {
    if (req.user?.role !== 'auditor') {
      return res.status(403).json({ error: 'Only approved auditors can run document audits.' });
    }

    const { text, policyRules } = req.body;
    if (!text || text.trim().length < 10) {
      return res.status(400).json({ error: 'text is required (min 10 characters)' });
    }

    const result = await aiService.auditDocument(text, policyRules || []);

    res.json({
      message: 'Text analysis complete',
      engine:  result.engine,
      result,
    });
  } catch (error) {
    console.error('Analyze text error:', error);
    res.status(500).json({ error: error.message || 'Analysis failed' });
  }
};

// ── POST /api/analysis/parse — extract metadata ───────────────────────────────

const parseDocumentText = async (req, res) => {
  try {
    if (req.user?.role !== 'auditor') {
      return res.status(403).json({ error: 'Only approved auditors can parse audit documents.' });
    }

    const { text } = req.body;
    if (!text) return res.status(400).json({ error: 'text is required' });
    const result = await aiService.parseDocument(text);
    res.json({ message: 'Document parsed', engine: result.engine, metadata: result });
  } catch (error) {
    res.status(500).json({ error: error.message || 'Parse failed' });
  }
};

// ── GET /api/analysis/:documentId/insights ────────────────────────────────────

const getDocumentInsights = async (req, res) => {
  try {
    const role = normalizeRole(req.user?.role);
    if (role === 'client') {
      return res.status(403).json({ error: 'Analysis reports are not available to client accounts.' });
    }

    const { documentId } = req.params;
    const { Document, DocumentAnalysis } = req.app.locals.models;
    const document = await Document.findByPk(documentId);
    if (!document) return res.status(404).json({ error: 'Document not found' });
    if (!userOwnsDocument(document, req.user?.id, req.user?.role)) {
      return res.status(403).json({ error: 'Access denied to this document analysis' });
    }
    const analysis = await DocumentAnalysis.findOne({ where: { documentId } });
    if (!analysis) return res.status(404).json({ error: 'No analysis found. Run analysis first.' });
    res.json({
      documentId,
      riskLevel:       analysis.riskFactors?.level || 'low',
      summary:         analysis.summary,
      recommendations: analysis.recommendations,
      results:         analysis.results,
      decision:        analysis.results?.decision || document.metadata?.latestAuditDecision || null,
      auditorComment:  analysis.results?.auditor_comment || null,
      analyzedAt:      analysis.completedAt,
      confidenceScore: Math.round((analysis.confidence || 0.95) * 100),
    });
  } catch (error) {
    res.status(500).json({ error: error.message || 'Failed to fetch insights' });
  }
};

// ── POST /api/analysis/bulk/analyze ──────────────────────────────────────────

const bulkAnalyze = async (req, res) => {
  try {
    if (req.user?.role !== 'auditor') {
      return res.status(403).json({ error: 'Only approved auditors can run document audits.' });
    }

    const { documentIds } = req.body;
    const { Document, DocumentAnalysis } = req.app.locals.models;

    if (!Array.isArray(documentIds) || documentIds.length === 0) {
      return res.status(400).json({ error: 'documentIds array is required' });
    }

    const results = [];
    const bundleEntries = [];
    for (const docId of documentIds) {
      try {
        const doc = await Document.findByPk(docId);
        if (!doc) { results.push({ documentId: docId, status: 'not_found' }); continue; }

        let text = null;
        if (doc.filePath) {
          text = await extractTextFromFile(doc.filePath, doc.mimeType);
          if (text) await doc.update({ extractedText: text.slice(0, 10000) });
        }
        if (!text) text = doc.extractedText;
        if (!text || text.trim().length < 25) {
          results.push({
            documentId: docId,
            status: 'failed',
            error: 'Could not read PDF content (file name is not used for audit).',
          });
          continue;
        }

        const result = await aiService.auditDocument(text, [], {
          contentOnly: true,
          filePath: doc.filePath,
        });
        let decision = buildAuditAnalysisSummary(result);
        const isSystemReport = reportLayout.isSystemGeneratedReport(text);
        if (isSystemReport) {
          decision = systemReportDecision(result);
        }

        await DocumentAnalysis.upsert({
          documentId: docId,
          analysisType:    'compliance_audit',
          status:          'completed',
          summary:         result.summary       || '',
          results: {
            compliance_score: result.compliance_score,
            overall_audit_score: result.overall_audit_score,
            overall_audit_status: result.overall_audit_status,
            overall_audit_breakdown: result.overall_audit_breakdown,
            ai_generated_percentage: result.ai_generated_percentage,
            ai_threshold_exceeded: result.ai_threshold_exceeded,
            ai_validity_percentage: result.ai_validity_percentage,
            ai_detection:     result.ai_detection,
            risk_level:       result.risk_level,
            missing_fields:   result.missing_fields,
            violations:       result.violations,
            inconsistencies:  result.inconsistencies,
            document_type:    result.document_type,
            organization_match: result.organization_match,
            document_inspection: result.document_inspection,
            dataset_baseline: result.dataset_baseline,
          },
          keywords:        result.missing_fields || [],
          recommendations: result.recommendations || [],
          riskFactors:     { level: result.risk_level },
          confidence:      result.ai_validity_percentage !== undefined ? (result.ai_validity_percentage / 100) : 0.95,
          model:           result.engine || 'rule-based-v2',
          performedBy:     req.user?.id || null,
          completedAt:     new Date(),
        });

        await doc.update({
          status: isSystemReport ? 'approved' : 'in_progress',
          ocrProcessed: Boolean(text) || doc.ocrProcessed,
          metadata: {
            ...(doc.metadata || {}),
            latestAuditDecision: decision,
            latestAuditSummary: result.summary,
            latestComplianceScore: result.compliance_score,
            latestOverallAuditScore: result.overall_audit_score,
            latestOverallAuditStatus: result.overall_audit_status,
            statusReason: decision.reason,
            statusTitle: decision.title,
            statusDetail: decision.detail,
            statusCode: decision.code,
            awaitingAuditorDecision: !isSystemReport,
          },
          lastModifiedBy: req.user?.id || null,
          lastModifiedAt: new Date(),
        });

        if (isSystemReport) {
          await resolveNeedsAuditNotifications(req.app.locals.models, docId);
        }

        if (result.organization_match) {
          bundleEntries.push({ documentId: docId, text, auditResult: result });
        }

        results.push({
          documentId: docId,
          status:     'success',
          documentStatus: isSystemReport ? 'approved' : 'in_progress',
          riskLevel:  result.risk_level,
          score:      result.compliance_score,
          overall_audit_score: result.overall_audit_score,
          overall_audit_status: result.overall_audit_status,
          ai_generated_percentage: result.ai_generated_percentage,
          ai_threshold_exceeded: result.ai_threshold_exceeded,
          ai_validity_percentage: result.ai_validity_percentage,
          engine:     result.engine,
        });
      } catch (err) {
        results.push({ documentId: docId, status: 'error', error: err.message });
      }
    }

    const shipmentCheck = shipmentConsistency.auditShipmentBundle(bundleEntries);

    res.json({
      message:    'Bulk analysis complete',
      successful: results.filter(r => r.status === 'success').length,
      failed:     results.filter(r => r.status === 'error').length,
      shipment_consistency: shipmentCheck,
      results,
    });
  } catch (error) {
    res.status(500).json({ error: error.message || 'Bulk analysis failed' });
  }
};

// ── GET /api/analysis/:documentId/status ─────────────────────────────────────

const getAnalysisStatus = async (req, res) => {
  try {
    const { documentId } = req.params;
    const { Document, DocumentAnalysis } = req.app.locals.models;
    const document = await Document.findByPk(documentId);
    if (!document) return res.status(404).json({ error: 'Document not found' });
    if (!userOwnsDocument(document, req.user?.id, req.user?.role)) {
      return res.status(403).json({ error: 'Access denied to this document analysis' });
    }
    const analysis = await DocumentAnalysis.findOne({ where: { documentId } });
    if (!analysis) return res.status(404).json({ error: 'No analysis found' });
    res.json({ documentId, status: 'completed', progress: 100, analysis });
  } catch (error) {
    res.status(500).json({ error: error.message || 'Failed to fetch status' });
  }
};

// ── GET /api/analysis/trend/history ──────────────────────────────────────────

const getAnalysisTrend = async (req, res) => {
  try {
    const { days = 30 } = req.query;
    const { Document, DocumentAnalysis } = req.app.locals.models;
    const options = {
      where: { completedAt: { [Op.gte]: new Date(Date.now() - days * 86400000) } },
      order: [['completedAt', 'ASC']],
    };
    if (['client', 'document_manager'].includes(req.user?.role)) {
      options.include = [{
        model: Document,
        attributes: [],
        required: true,
        where: { uploadedBy: req.user.id },
      }];
    }
    const analyses = await DocumentAnalysis.findAll(options);
    const trendData = {};
    analyses.forEach(a => {
      const date = a.completedAt?.toISOString().split('T')[0];
      if (!date) return;
      if (!trendData[date]) trendData[date] = { total: 0, highRisk: 0 };
      trendData[date].total++;
      if ((a.riskFactors?.level || a.results?.risk_level) === 'high') trendData[date].highRisk++;
    });
    res.json({ data: Object.entries(trendData).map(([date, s]) => ({ date, ...s })), totalAnalyzed: analyses.length });
  } catch (error) {
    res.status(500).json({ error: error.message || 'Failed to fetch trend' });
  }
};

// ── GET /api/analysis/stats/overview ─────────────────────────────────────────

const getAnalysisStats = async (req, res) => {
  try {
    const { Document, DocumentAnalysis } = req.app.locals.models;
    const { averageOverallScore } = require('../services/auditScoreService');
    const { normalizeRole } = require('../utils/roles');
    const { documentWhereForUser } = require('../utils/ownerScope');
    const Op = require('sequelize').Op;

    const role = normalizeRole(req.user?.role);
    const where = { status: 'completed' };

    if (role === 'client') {
      const ownedDocs = await Document.findAll({
        where: documentWhereForUser({ id: req.user.id, role }),
        attributes: ['id'],
      });
      const docIds = ownedDocs.map(d => d.id);
      where.documentId = docIds.length ? docIds : { [Op.in]: [] };
    }

    const all = await DocumentAnalysis.findAll({ where });
    res.json({
      totalAnalyzed: all.length,
      averageConfidence: 95,
      averageOverallAuditScore: averageOverallScore(all),
      riskDistribution: {
        high: all.filter(a => (a.riskFactors?.level || a.results?.risk_level) === 'high').length,
        medium: all.filter(a => (a.riskFactors?.level || a.results?.risk_level) === 'medium').length,
        low: all.filter(a => (a.riskFactors?.level || a.results?.risk_level || 'low') === 'low').length,
      },
      aiEngine: process.env.OPENAI_API_KEY && process.env.OPENAI_API_KEY !== 'your-openai-key'
        ? 'openai+rules' : 'rule-based-v2',
    });
  } catch (error) {
    res.status(500).json({ error: error.message || 'Failed to fetch stats' });
  }
};

const getEvaluationMetrics = async (req, res) => {
  try {
    const path = require('path');
    const fs = require('fs');
    const resultsDir = path.join(__dirname, '..', 'data', 'training', 'evaluation', 'results');
    const tfidfPath = path.join(resultsDir, 'tfidf_evaluation.json');
    const fullPath = path.join(resultsDir, 'full_audit_evaluation.json');

    if (!fs.existsSync(tfidfPath)) {
      return res.status(404).json({
        error: 'Evaluation not run yet. Execute: cd backend && npm run evaluate:full',
      });
    }

    const tfidf = JSON.parse(fs.readFileSync(tfidfPath, 'utf8'));
    const payload = {
      algorithm: tfidf.algorithm,
      generated_at: tfidf.generated_at,
      reference_documents: tfidf.reference_documents,
      metrics: tfidf.evaluation_modes.full_corpus.metrics,
      confusion_matrix: tfidf.evaluation_modes.full_corpus.confusion_matrix_top1,
      per_class: tfidf.evaluation_modes.full_corpus.per_class,
      leave_one_out: tfidf.evaluation_modes.leave_one_out.metrics,
    };

    if (fs.existsSync(fullPath)) {
      const full = JSON.parse(fs.readFileSync(fullPath, 'utf8'));
      payload.pipeline_accuracy = full.pipeline && full.pipeline.accuracy;
      payload.business_value = full.business_value;
      payload.architecture_layers = full.architecture_layers;
    }

    res.json(payload);
  } catch (error) {
    res.status(500).json({ error: error.message || 'Failed to load evaluation metrics' });
  }
};

// ── GET /api/analysis/:documentId/export — download audit analysis report (PDF) ─

const exportDocumentAnalysis = async (req, res) => {
  try {
    const role = normalizeRole(req.user?.role);
    if (role === 'client') {
      return res.status(403).json({ error: 'Analysis reports are not available to client accounts.' });
    }

    const { documentId } = req.params;
    const { format = 'PDF' } = req.query;
    const { Document, DocumentAnalysis, User } = req.app.locals.models;

    const document = await Document.findByPk(documentId);
    if (!document) return res.status(404).json({ error: 'Document not found' });
    if (!userOwnsDocument(document, req.user?.id, req.user?.role)) {
      return res.status(403).json({ error: 'Access denied to this document analysis' });
    }

    const analysis = await DocumentAnalysis.findOne({ where: { documentId } });
    if (!analysis) {
      return res.status(404).json({ error: 'No audit analysis found. The document must be audited first.' });
    }

    const roleNorm = normalizeRole(req.user?.role);
    const fmtUpper = String(format).toUpperCase();
    const annotated = fmtUpper === 'ANNOTATED';
    const formatKey = annotated ? 'pdf'
      : fmtUpper === 'PDF' ? 'pdf'
      : fmtUpper === 'EXCEL' || fmtUpper === 'XLSX' ? 'excel'
      : fmtUpper.toLowerCase();
    if (!isExportFormatAllowed(roleNorm, formatKey)) {
      return res.status(403).json({
        error: `Your role can only export reports as: ${allowedExportFormats(roleNorm).join(', ')}`,
      });
    }

    const meta = document.metadata || {};
    const auditorId = analysis.performedBy || meta.latestAuditDecision?.updatedBy || null;
    const auditorUser = auditorId ? await User.findByPk(auditorId, { attributes: ['id', 'fullName', 'email'] }) : null;
    const preparedBy = req.user?.fullName
      ? `${req.user.fullName} (${req.user.role})`
      : req.user?.email || 'System';
    const isClient = roleNorm === 'client';

    if (formatKey !== 'pdf') {
      const results = analysis.results || {};
      const lines = [
        '='.repeat(60),
        'SIFCO — SUPER INTERNATIONAL FREIGHT',
        'DOCUMENT AUDIT ANALYSIS',
        '='.repeat(60),
        '',
        `Document    : ${document.title || document.fileName}`,
        `Status      : ${document.status}`,
        `Compliance  : ${results.compliance_score ?? meta.latestComplianceScore ?? '—'}%`,
        `Overall     : ${results.overall_audit_score ?? meta.latestOverallAuditScore ?? '—'}%`,
        `Risk        : ${results.risk_level || analysis.riskFactors?.level || '—'}`,
      ];
      if (!isClient) {
        lines.push(`Generated by: ${preparedBy}`);
      }
      lines.push(
        `Generated   : ${new Date().toLocaleString()}`,
        '',
        '='.repeat(60),
        'SUMMARY',
        '='.repeat(60),
        '',
        analysis.summary || meta.latestAuditSummary || 'No summary available.',
        '',
        '='.repeat(60),
        `Super International Freight / SIFCO — Confidential  |  Exported ${new Date().toLocaleString()}`,
      );
      res.setHeader('Content-Type', 'text/plain; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename="audit_analysis_${documentId.slice(0, 8)}.txt"`);
      return res.send(lines.join('\n'));
    }

    streamDocumentAnalysisPdf(res, {
      document: document.toJSON ? document.toJSON() : document,
      analysis: analysis.toJSON ? analysis.toJSON() : analysis,
      preparedBy: isClient ? null : preparedBy,
      auditorUser: auditorUser?.toJSON ? auditorUser.toJSON() : auditorUser,
      annotated,
      exportedByRole: roleNorm,
    });
  } catch (error) {
    console.error('Export document analysis error:', error);
    if (!res.headersSent) {
      res.status(500).json({ error: error.message || 'Export failed' });
    }
  }
};

module.exports = {
  analyzeDocument,
  analyzeText,
  parseDocumentText,
  getDocumentInsights,
  exportDocumentAnalysis,
  bulkAnalyze,
  getAnalysisStatus,
  getAnalysisTrend,
  getAnalysisStats,
  getEvaluationMetrics,
};
